version: '3.8'

services:
  web:
    build: .
    command: bash /app/entrypoint.sh
    volumes:
      - .:/app
      # Block local migrations from overriding container
      - /app/main/migrations
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEBUG=True
      # PASTE YOUR MONGO URL HERE FOR LOCAL DOCKER
      - MONGO_URL=${MONGO_URL} 
    env_file:
      - .env