services:
  - type: web
    name: itestoria
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn itestoria.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
    staticPublishPath: staticfiles

